// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "UseIncenseMessage.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Networking { public struct Requests { public struct Messages { }}}}

public func == (lhs: Pogoprotos.Networking.Requests.Messages.UseIncenseMessage, rhs: Pogoprotos.Networking.Requests.Messages.UseIncenseMessage) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasIncenseType == rhs.hasIncenseType) && (!lhs.hasIncenseType || lhs.incenseType == rhs.incenseType)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Pogoprotos.Networking.Requests.Messages {
  public struct UseIncenseMessageRoot {
    public static var sharedInstance : UseIncenseMessageRoot {
     struct Static {
         static let instance : UseIncenseMessageRoot = UseIncenseMessageRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
      Pogoprotos.Inventory.Item.ItemIdRoot.sharedInstance.registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class UseIncenseMessage : GeneratedMessage, GeneratedMessageProtocol {
    public private(set) var incenseType:Pogoprotos.Inventory.Item.ItemId = Pogoprotos.Inventory.Item.ItemId.ItemUnknown
    public private(set) var hasIncenseType:Bool = false
    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasIncenseType {
        try output.writeEnum(1, value:incenseType.rawValue)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if (hasIncenseType) {
        serialize_size += incenseType.rawValue.computeEnumSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Networking.Requests.Messages.UseIncenseMessage> {
      var mergedArray = Array<Pogoprotos.Networking.Requests.Messages.UseIncenseMessage>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage? {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Networking.Requests.Messages.UseIncenseMessageRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
      return Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.classBuilder() as! Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder
    }
    public func getBuilder() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
      return classBuilder() as! Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Networking.Requests.Messages.UseIncenseMessage) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasIncenseType {
        jsonMap["incenseType"] = incenseType.toString()
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
      return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if (hasIncenseType) {
        output += "\(indent) incenseType: \(incenseType.description)\n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIncenseType {
               hashCode = (hashCode &* 31) &+ Int(incenseType.rawValue)
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Networking.Requests.Messages.UseIncenseMessage"
    }
    override public func className() -> String {
        return "Pogoprotos.Networking.Requests.Messages.UseIncenseMessage"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Networking.Requests.Messages.UseIncenseMessage = Pogoprotos.Networking.Requests.Messages.UseIncenseMessage()
      public func getMessage() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
          return builderResult
      }

      required override public init () {
         super.init()
      }
        public var hasIncenseType:Bool{
            get {
                return builderResult.hasIncenseType
            }
        }
        public var incenseType:Pogoprotos.Inventory.Item.ItemId {
            get {
                return builderResult.incenseType
            }
            set (value) {
                builderResult.hasIncenseType = true
                builderResult.incenseType = value
            }
        }
        public func setIncenseType(value:Pogoprotos.Inventory.Item.ItemId) -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
          self.incenseType = value
          return self
        }
        public func clearIncenseType() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
           builderResult.hasIncenseType = false
           builderResult.incenseType = .ItemUnknown
           return self
        }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        builderResult = Pogoprotos.Networking.Requests.Messages.UseIncenseMessage()
        return self
      }
      override public func clone() throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage {
        let returnMe:Pogoprotos.Networking.Requests.Messages.UseIncenseMessage = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Networking.Requests.Messages.UseIncenseMessage) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        if other == Pogoprotos.Networking.Requests.Messages.UseIncenseMessage() {
         return self
        }
        if other.hasIncenseType {
             incenseType = other.incenseType
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            let valueIntincenseType = try input.readEnum()
            if let enumsincenseType = Pogoprotos.Inventory.Item.ItemId(rawValue:valueIntincenseType){
                 incenseType = enumsincenseType
            } else {
                 try unknownFieldsBuilder.mergeVarintField(1, value:Int64(valueIntincenseType))
            }

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        let resultDecodedBuilder = Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder()
        if let jsonValueIncenseType = jsonMap["incenseType"] as? String {
          resultDecodedBuilder.incenseType = try Pogoprotos.Inventory.Item.ItemId.fromString(jsonValueIncenseType)
        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Networking.Requests.Messages.UseIncenseMessage.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
