// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "PokemonFamilyId.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Enums { }}

public extension Pogoprotos.Enums {
  public struct PokemonFamilyIdRoot {
    public static var sharedInstance : PokemonFamilyIdRoot {
     struct Static {
         static let instance : PokemonFamilyIdRoot = PokemonFamilyIdRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }



  //Enum type declaration start 

  public enum PokemonFamilyId:Int32, CustomDebugStringConvertible, CustomStringConvertible {
    case FamilyUnset = 0
    case FamilyBulbasaur = 1
    case FamilyCharmander = 4
    case FamilySquirtle = 7
    case FamilyCaterpie = 10
    case FamilyWeedle = 13
    case FamilyPidgey = 16
    case FamilyRattata = 19
    case FamilySpearow = 21
    case FamilyEkans = 23
    case FamilyPikachu = 25
    case FamilySandshrew = 27
    case FamilyNidoranFemale = 29
    case FamilyNidoranMale = 32
    case FamilyClefairy = 35
    case FamilyVulpix = 37
    case FamilyJigglypuff = 39
    case FamilyZubat = 41
    case FamilyOddish = 43
    case FamilyParas = 46
    case FamilyVenonat = 48
    case FamilyDiglett = 50
    case FamilyMeowth = 52
    case FamilyPsyduck = 54
    case FamilyMankey = 56
    case FamilyGrowlithe = 58
    case FamilyPoliwag = 60
    case FamilyAbra = 63
    case FamilyMachop = 66
    case FamilyBellsprout = 69
    case FamilyTentacool = 72
    case FamilyGeodude = 74
    case FamilyPonyta = 77
    case FamilySlowpoke = 79
    case FamilyMagnemite = 81
    case FamilyFarfetchd = 83
    case FamilyDoduo = 84
    case FamilySeel = 86
    case FamilyGrimer = 88
    case FamilyShellder = 90
    case FamilyGastly = 92
    case FamilyOnix = 95
    case FamilyDrowzee = 96
    case FamilyHypno = 97
    case FamilyKrabby = 98
    case FamilyVoltorb = 100
    case FamilyExeggcute = 102
    case FamilyCubone = 104
    case FamilyHitmonlee = 106
    case FamilyHitmonchan = 107
    case FamilyLickitung = 108
    case FamilyKoffing = 109
    case FamilyRhyhorn = 111
    case FamilyChansey = 113
    case FamilyTangela = 114
    case FamilyKangaskhan = 115
    case FamilyHorsea = 116
    case FamilyGoldeen = 118
    case FamilyStaryu = 120
    case FamilyMrMime = 122
    case FamilyScyther = 123
    case FamilyJynx = 124
    case FamilyElectabuzz = 125
    case FamilyMagmar = 126
    case FamilyPinsir = 127
    case FamilyTauros = 128
    case FamilyMagikarp = 129
    case FamilyLapras = 131
    case FamilyDitto = 132
    case FamilyEevee = 133
    case FamilyPorygon = 137
    case FamilyOmanyte = 138
    case FamilyKabuto = 140
    case FamilyAerodactyl = 142
    case FamilySnorlax = 143
    case FamilyArticuno = 144
    case FamilyZapdos = 145
    case FamilyMoltres = 146
    case FamilyDratini = 147
    case FamilyMewtwo = 150
    case FamilyMew = 151
    public func toString() -> String {
      switch self {
      case .FamilyUnset: return "FAMILY_UNSET"
      case .FamilyBulbasaur: return "FAMILY_BULBASAUR"
      case .FamilyCharmander: return "FAMILY_CHARMANDER"
      case .FamilySquirtle: return "FAMILY_SQUIRTLE"
      case .FamilyCaterpie: return "FAMILY_CATERPIE"
      case .FamilyWeedle: return "FAMILY_WEEDLE"
      case .FamilyPidgey: return "FAMILY_PIDGEY"
      case .FamilyRattata: return "FAMILY_RATTATA"
      case .FamilySpearow: return "FAMILY_SPEAROW"
      case .FamilyEkans: return "FAMILY_EKANS"
      case .FamilyPikachu: return "FAMILY_PIKACHU"
      case .FamilySandshrew: return "FAMILY_SANDSHREW"
      case .FamilyNidoranFemale: return "FAMILY_NIDORAN_FEMALE"
      case .FamilyNidoranMale: return "FAMILY_NIDORAN_MALE"
      case .FamilyClefairy: return "FAMILY_CLEFAIRY"
      case .FamilyVulpix: return "FAMILY_VULPIX"
      case .FamilyJigglypuff: return "FAMILY_JIGGLYPUFF"
      case .FamilyZubat: return "FAMILY_ZUBAT"
      case .FamilyOddish: return "FAMILY_ODDISH"
      case .FamilyParas: return "FAMILY_PARAS"
      case .FamilyVenonat: return "FAMILY_VENONAT"
      case .FamilyDiglett: return "FAMILY_DIGLETT"
      case .FamilyMeowth: return "FAMILY_MEOWTH"
      case .FamilyPsyduck: return "FAMILY_PSYDUCK"
      case .FamilyMankey: return "FAMILY_MANKEY"
      case .FamilyGrowlithe: return "FAMILY_GROWLITHE"
      case .FamilyPoliwag: return "FAMILY_POLIWAG"
      case .FamilyAbra: return "FAMILY_ABRA"
      case .FamilyMachop: return "FAMILY_MACHOP"
      case .FamilyBellsprout: return "FAMILY_BELLSPROUT"
      case .FamilyTentacool: return "FAMILY_TENTACOOL"
      case .FamilyGeodude: return "FAMILY_GEODUDE"
      case .FamilyPonyta: return "FAMILY_PONYTA"
      case .FamilySlowpoke: return "FAMILY_SLOWPOKE"
      case .FamilyMagnemite: return "FAMILY_MAGNEMITE"
      case .FamilyFarfetchd: return "FAMILY_FARFETCHD"
      case .FamilyDoduo: return "FAMILY_DODUO"
      case .FamilySeel: return "FAMILY_SEEL"
      case .FamilyGrimer: return "FAMILY_GRIMER"
      case .FamilyShellder: return "FAMILY_SHELLDER"
      case .FamilyGastly: return "FAMILY_GASTLY"
      case .FamilyOnix: return "FAMILY_ONIX"
      case .FamilyDrowzee: return "FAMILY_DROWZEE"
      case .FamilyHypno: return "FAMILY_HYPNO"
      case .FamilyKrabby: return "FAMILY_KRABBY"
      case .FamilyVoltorb: return "FAMILY_VOLTORB"
      case .FamilyExeggcute: return "FAMILY_EXEGGCUTE"
      case .FamilyCubone: return "FAMILY_CUBONE"
      case .FamilyHitmonlee: return "FAMILY_HITMONLEE"
      case .FamilyHitmonchan: return "FAMILY_HITMONCHAN"
      case .FamilyLickitung: return "FAMILY_LICKITUNG"
      case .FamilyKoffing: return "FAMILY_KOFFING"
      case .FamilyRhyhorn: return "FAMILY_RHYHORN"
      case .FamilyChansey: return "FAMILY_CHANSEY"
      case .FamilyTangela: return "FAMILY_TANGELA"
      case .FamilyKangaskhan: return "FAMILY_KANGASKHAN"
      case .FamilyHorsea: return "FAMILY_HORSEA"
      case .FamilyGoldeen: return "FAMILY_GOLDEEN"
      case .FamilyStaryu: return "FAMILY_STARYU"
      case .FamilyMrMime: return "FAMILY_MR_MIME"
      case .FamilyScyther: return "FAMILY_SCYTHER"
      case .FamilyJynx: return "FAMILY_JYNX"
      case .FamilyElectabuzz: return "FAMILY_ELECTABUZZ"
      case .FamilyMagmar: return "FAMILY_MAGMAR"
      case .FamilyPinsir: return "FAMILY_PINSIR"
      case .FamilyTauros: return "FAMILY_TAUROS"
      case .FamilyMagikarp: return "FAMILY_MAGIKARP"
      case .FamilyLapras: return "FAMILY_LAPRAS"
      case .FamilyDitto: return "FAMILY_DITTO"
      case .FamilyEevee: return "FAMILY_EEVEE"
      case .FamilyPorygon: return "FAMILY_PORYGON"
      case .FamilyOmanyte: return "FAMILY_OMANYTE"
      case .FamilyKabuto: return "FAMILY_KABUTO"
      case .FamilyAerodactyl: return "FAMILY_AERODACTYL"
      case .FamilySnorlax: return "FAMILY_SNORLAX"
      case .FamilyArticuno: return "FAMILY_ARTICUNO"
      case .FamilyZapdos: return "FAMILY_ZAPDOS"
      case .FamilyMoltres: return "FAMILY_MOLTRES"
      case .FamilyDratini: return "FAMILY_DRATINI"
      case .FamilyMewtwo: return "FAMILY_MEWTWO"
      case .FamilyMew: return "FAMILY_MEW"
      }
    }
    public static func fromString(str:String) throws -> Pogoprotos.Enums.PokemonFamilyId {
      switch str {
      case "FAMILY_UNSET":  return .FamilyUnset
      case "FAMILY_BULBASAUR":  return .FamilyBulbasaur
      case "FAMILY_CHARMANDER":  return .FamilyCharmander
      case "FAMILY_SQUIRTLE":  return .FamilySquirtle
      case "FAMILY_CATERPIE":  return .FamilyCaterpie
      case "FAMILY_WEEDLE":  return .FamilyWeedle
      case "FAMILY_PIDGEY":  return .FamilyPidgey
      case "FAMILY_RATTATA":  return .FamilyRattata
      case "FAMILY_SPEAROW":  return .FamilySpearow
      case "FAMILY_EKANS":  return .FamilyEkans
      case "FAMILY_PIKACHU":  return .FamilyPikachu
      case "FAMILY_SANDSHREW":  return .FamilySandshrew
      case "FAMILY_NIDORAN_FEMALE":  return .FamilyNidoranFemale
      case "FAMILY_NIDORAN_MALE":  return .FamilyNidoranMale
      case "FAMILY_CLEFAIRY":  return .FamilyClefairy
      case "FAMILY_VULPIX":  return .FamilyVulpix
      case "FAMILY_JIGGLYPUFF":  return .FamilyJigglypuff
      case "FAMILY_ZUBAT":  return .FamilyZubat
      case "FAMILY_ODDISH":  return .FamilyOddish
      case "FAMILY_PARAS":  return .FamilyParas
      case "FAMILY_VENONAT":  return .FamilyVenonat
      case "FAMILY_DIGLETT":  return .FamilyDiglett
      case "FAMILY_MEOWTH":  return .FamilyMeowth
      case "FAMILY_PSYDUCK":  return .FamilyPsyduck
      case "FAMILY_MANKEY":  return .FamilyMankey
      case "FAMILY_GROWLITHE":  return .FamilyGrowlithe
      case "FAMILY_POLIWAG":  return .FamilyPoliwag
      case "FAMILY_ABRA":  return .FamilyAbra
      case "FAMILY_MACHOP":  return .FamilyMachop
      case "FAMILY_BELLSPROUT":  return .FamilyBellsprout
      case "FAMILY_TENTACOOL":  return .FamilyTentacool
      case "FAMILY_GEODUDE":  return .FamilyGeodude
      case "FAMILY_PONYTA":  return .FamilyPonyta
      case "FAMILY_SLOWPOKE":  return .FamilySlowpoke
      case "FAMILY_MAGNEMITE":  return .FamilyMagnemite
      case "FAMILY_FARFETCHD":  return .FamilyFarfetchd
      case "FAMILY_DODUO":  return .FamilyDoduo
      case "FAMILY_SEEL":  return .FamilySeel
      case "FAMILY_GRIMER":  return .FamilyGrimer
      case "FAMILY_SHELLDER":  return .FamilyShellder
      case "FAMILY_GASTLY":  return .FamilyGastly
      case "FAMILY_ONIX":  return .FamilyOnix
      case "FAMILY_DROWZEE":  return .FamilyDrowzee
      case "FAMILY_HYPNO":  return .FamilyHypno
      case "FAMILY_KRABBY":  return .FamilyKrabby
      case "FAMILY_VOLTORB":  return .FamilyVoltorb
      case "FAMILY_EXEGGCUTE":  return .FamilyExeggcute
      case "FAMILY_CUBONE":  return .FamilyCubone
      case "FAMILY_HITMONLEE":  return .FamilyHitmonlee
      case "FAMILY_HITMONCHAN":  return .FamilyHitmonchan
      case "FAMILY_LICKITUNG":  return .FamilyLickitung
      case "FAMILY_KOFFING":  return .FamilyKoffing
      case "FAMILY_RHYHORN":  return .FamilyRhyhorn
      case "FAMILY_CHANSEY":  return .FamilyChansey
      case "FAMILY_TANGELA":  return .FamilyTangela
      case "FAMILY_KANGASKHAN":  return .FamilyKangaskhan
      case "FAMILY_HORSEA":  return .FamilyHorsea
      case "FAMILY_GOLDEEN":  return .FamilyGoldeen
      case "FAMILY_STARYU":  return .FamilyStaryu
      case "FAMILY_MR_MIME":  return .FamilyMrMime
      case "FAMILY_SCYTHER":  return .FamilyScyther
      case "FAMILY_JYNX":  return .FamilyJynx
      case "FAMILY_ELECTABUZZ":  return .FamilyElectabuzz
      case "FAMILY_MAGMAR":  return .FamilyMagmar
      case "FAMILY_PINSIR":  return .FamilyPinsir
      case "FAMILY_TAUROS":  return .FamilyTauros
      case "FAMILY_MAGIKARP":  return .FamilyMagikarp
      case "FAMILY_LAPRAS":  return .FamilyLapras
      case "FAMILY_DITTO":  return .FamilyDitto
      case "FAMILY_EEVEE":  return .FamilyEevee
      case "FAMILY_PORYGON":  return .FamilyPorygon
      case "FAMILY_OMANYTE":  return .FamilyOmanyte
      case "FAMILY_KABUTO":  return .FamilyKabuto
      case "FAMILY_AERODACTYL":  return .FamilyAerodactyl
      case "FAMILY_SNORLAX":  return .FamilySnorlax
      case "FAMILY_ARTICUNO":  return .FamilyArticuno
      case "FAMILY_ZAPDOS":  return .FamilyZapdos
      case "FAMILY_MOLTRES":  return .FamilyMoltres
      case "FAMILY_DRATINI":  return .FamilyDratini
      case "FAMILY_MEWTWO":  return .FamilyMewtwo
      case "FAMILY_MEW":  return .FamilyMew
      default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
      }
    }
    public var debugDescription:String { return getDescription() }
    public var description:String { return getDescription() }
    private func getDescription() -> String { 
        switch self {
            case .FamilyUnset: return ".FamilyUnset"
            case .FamilyBulbasaur: return ".FamilyBulbasaur"
            case .FamilyCharmander: return ".FamilyCharmander"
            case .FamilySquirtle: return ".FamilySquirtle"
            case .FamilyCaterpie: return ".FamilyCaterpie"
            case .FamilyWeedle: return ".FamilyWeedle"
            case .FamilyPidgey: return ".FamilyPidgey"
            case .FamilyRattata: return ".FamilyRattata"
            case .FamilySpearow: return ".FamilySpearow"
            case .FamilyEkans: return ".FamilyEkans"
            case .FamilyPikachu: return ".FamilyPikachu"
            case .FamilySandshrew: return ".FamilySandshrew"
            case .FamilyNidoranFemale: return ".FamilyNidoranFemale"
            case .FamilyNidoranMale: return ".FamilyNidoranMale"
            case .FamilyClefairy: return ".FamilyClefairy"
            case .FamilyVulpix: return ".FamilyVulpix"
            case .FamilyJigglypuff: return ".FamilyJigglypuff"
            case .FamilyZubat: return ".FamilyZubat"
            case .FamilyOddish: return ".FamilyOddish"
            case .FamilyParas: return ".FamilyParas"
            case .FamilyVenonat: return ".FamilyVenonat"
            case .FamilyDiglett: return ".FamilyDiglett"
            case .FamilyMeowth: return ".FamilyMeowth"
            case .FamilyPsyduck: return ".FamilyPsyduck"
            case .FamilyMankey: return ".FamilyMankey"
            case .FamilyGrowlithe: return ".FamilyGrowlithe"
            case .FamilyPoliwag: return ".FamilyPoliwag"
            case .FamilyAbra: return ".FamilyAbra"
            case .FamilyMachop: return ".FamilyMachop"
            case .FamilyBellsprout: return ".FamilyBellsprout"
            case .FamilyTentacool: return ".FamilyTentacool"
            case .FamilyGeodude: return ".FamilyGeodude"
            case .FamilyPonyta: return ".FamilyPonyta"
            case .FamilySlowpoke: return ".FamilySlowpoke"
            case .FamilyMagnemite: return ".FamilyMagnemite"
            case .FamilyFarfetchd: return ".FamilyFarfetchd"
            case .FamilyDoduo: return ".FamilyDoduo"
            case .FamilySeel: return ".FamilySeel"
            case .FamilyGrimer: return ".FamilyGrimer"
            case .FamilyShellder: return ".FamilyShellder"
            case .FamilyGastly: return ".FamilyGastly"
            case .FamilyOnix: return ".FamilyOnix"
            case .FamilyDrowzee: return ".FamilyDrowzee"
            case .FamilyHypno: return ".FamilyHypno"
            case .FamilyKrabby: return ".FamilyKrabby"
            case .FamilyVoltorb: return ".FamilyVoltorb"
            case .FamilyExeggcute: return ".FamilyExeggcute"
            case .FamilyCubone: return ".FamilyCubone"
            case .FamilyHitmonlee: return ".FamilyHitmonlee"
            case .FamilyHitmonchan: return ".FamilyHitmonchan"
            case .FamilyLickitung: return ".FamilyLickitung"
            case .FamilyKoffing: return ".FamilyKoffing"
            case .FamilyRhyhorn: return ".FamilyRhyhorn"
            case .FamilyChansey: return ".FamilyChansey"
            case .FamilyTangela: return ".FamilyTangela"
            case .FamilyKangaskhan: return ".FamilyKangaskhan"
            case .FamilyHorsea: return ".FamilyHorsea"
            case .FamilyGoldeen: return ".FamilyGoldeen"
            case .FamilyStaryu: return ".FamilyStaryu"
            case .FamilyMrMime: return ".FamilyMrMime"
            case .FamilyScyther: return ".FamilyScyther"
            case .FamilyJynx: return ".FamilyJynx"
            case .FamilyElectabuzz: return ".FamilyElectabuzz"
            case .FamilyMagmar: return ".FamilyMagmar"
            case .FamilyPinsir: return ".FamilyPinsir"
            case .FamilyTauros: return ".FamilyTauros"
            case .FamilyMagikarp: return ".FamilyMagikarp"
            case .FamilyLapras: return ".FamilyLapras"
            case .FamilyDitto: return ".FamilyDitto"
            case .FamilyEevee: return ".FamilyEevee"
            case .FamilyPorygon: return ".FamilyPorygon"
            case .FamilyOmanyte: return ".FamilyOmanyte"
            case .FamilyKabuto: return ".FamilyKabuto"
            case .FamilyAerodactyl: return ".FamilyAerodactyl"
            case .FamilySnorlax: return ".FamilySnorlax"
            case .FamilyArticuno: return ".FamilyArticuno"
            case .FamilyZapdos: return ".FamilyZapdos"
            case .FamilyMoltres: return ".FamilyMoltres"
            case .FamilyDratini: return ".FamilyDratini"
            case .FamilyMewtwo: return ".FamilyMewtwo"
            case .FamilyMew: return ".FamilyMew"
        }
    }
  }

  //Enum type declaration end 

}

// @@protoc_insertion_point(global_scope)
