// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "GetInventoryResponse.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Networking { public struct Responses { }}}

public func == (lhs: Pogoprotos.Networking.Responses.GetInventoryResponse, rhs: Pogoprotos.Networking.Responses.GetInventoryResponse) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasSuccess == rhs.hasSuccess) && (!lhs.hasSuccess || lhs.success == rhs.success)
  fieldCheck = fieldCheck && (lhs.hasInventoryDelta == rhs.hasInventoryDelta) && (!lhs.hasInventoryDelta || lhs.inventoryDelta == rhs.inventoryDelta)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Pogoprotos.Networking.Responses {
  public struct GetInventoryResponseRoot {
    public static var sharedInstance : GetInventoryResponseRoot {
     struct Static {
         static let instance : GetInventoryResponseRoot = GetInventoryResponseRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
      Pogoprotos.Inventory.InventoryDeltaRoot.sharedInstance.registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class GetInventoryResponse : GeneratedMessage, GeneratedMessageProtocol {
    public private(set) var hasSuccess:Bool = false
    public private(set) var success:Bool = false

    public private(set) var hasInventoryDelta:Bool = false
    public private(set) var inventoryDelta:Pogoprotos.Inventory.InventoryDelta!
    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasSuccess {
        try output.writeBool(1, value:success)
      }
      if hasInventoryDelta {
        try output.writeMessage(2, value:inventoryDelta)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasSuccess {
        serialize_size += success.computeBoolSize(1)
      }
      if hasInventoryDelta {
          if let varSizeinventoryDelta = inventoryDelta?.computeMessageSize(2) {
              serialize_size += varSizeinventoryDelta
          }
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Networking.Responses.GetInventoryResponse> {
      var mergedArray = Array<Pogoprotos.Networking.Responses.GetInventoryResponse>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse? {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Networking.Responses.GetInventoryResponseRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
      return Pogoprotos.Networking.Responses.GetInventoryResponse.classBuilder() as! Pogoprotos.Networking.Responses.GetInventoryResponse.Builder
    }
    public func getBuilder() -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
      return classBuilder() as! Pogoprotos.Networking.Responses.GetInventoryResponse.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Responses.GetInventoryResponse.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Responses.GetInventoryResponse.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Networking.Responses.GetInventoryResponse) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasSuccess {
        jsonMap["success"] = success
      }
      if hasInventoryDelta {
        jsonMap["inventoryDelta"] = try inventoryDelta.encode()
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
      return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasSuccess {
        output += "\(indent) success: \(success) \n"
      }
      if hasInventoryDelta {
        output += "\(indent) inventoryDelta {\n"
        if let outDescInventoryDelta = inventoryDelta {
          output += try outDescInventoryDelta.getDescription("\(indent)  ")
        }
        output += "\(indent) }\n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasSuccess {
               hashCode = (hashCode &* 31) &+ success.hashValue
            }
            if hasInventoryDelta {
                if let hashValueinventoryDelta = inventoryDelta?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueinventoryDelta
                }
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Networking.Responses.GetInventoryResponse"
    }
    override public func className() -> String {
        return "Pogoprotos.Networking.Responses.GetInventoryResponse"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Networking.Responses.GetInventoryResponse.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Networking.Responses.GetInventoryResponse = Pogoprotos.Networking.Responses.GetInventoryResponse()
      public func getMessage() -> Pogoprotos.Networking.Responses.GetInventoryResponse {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasSuccess:Bool {
           get {
                return builderResult.hasSuccess
           }
      }
      public var success:Bool {
           get {
                return builderResult.success
           }
           set (value) {
               builderResult.hasSuccess = true
               builderResult.success = value
           }
      }
      public func setSuccess(value:Bool) -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        self.success = value
        return self
      }
      public func clearSuccess() -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder{
           builderResult.hasSuccess = false
           builderResult.success = false
           return self
      }
      public var hasInventoryDelta:Bool {
           get {
               return builderResult.hasInventoryDelta
           }
      }
      public var inventoryDelta:Pogoprotos.Inventory.InventoryDelta! {
           get {
               if inventoryDeltaBuilder_ != nil {
                  builderResult.inventoryDelta = inventoryDeltaBuilder_.getMessage()
               }
               return builderResult.inventoryDelta
           }
           set (value) {
               builderResult.hasInventoryDelta = true
               builderResult.inventoryDelta = value
           }
      }
      private var inventoryDeltaBuilder_:Pogoprotos.Inventory.InventoryDelta.Builder! {
           didSet {
              builderResult.hasInventoryDelta = true
           }
      }
      public func getInventoryDeltaBuilder() -> Pogoprotos.Inventory.InventoryDelta.Builder {
        if inventoryDeltaBuilder_ == nil {
           inventoryDeltaBuilder_ = Pogoprotos.Inventory.InventoryDelta.Builder()
           builderResult.inventoryDelta = inventoryDeltaBuilder_.getMessage()
           if inventoryDelta != nil {
              try! inventoryDeltaBuilder_.mergeFrom(inventoryDelta)
           }
        }
        return inventoryDeltaBuilder_
      }
      public func setInventoryDelta(value:Pogoprotos.Inventory.InventoryDelta!) -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        self.inventoryDelta = value
        return self
      }
      public func mergeInventoryDelta(value:Pogoprotos.Inventory.InventoryDelta) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        if builderResult.hasInventoryDelta {
          builderResult.inventoryDelta = try Pogoprotos.Inventory.InventoryDelta.builderWithPrototype(builderResult.inventoryDelta).mergeFrom(value).buildPartial()
        } else {
          builderResult.inventoryDelta = value
        }
        builderResult.hasInventoryDelta = true
        return self
      }
      public func clearInventoryDelta() -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        inventoryDeltaBuilder_ = nil
        builderResult.hasInventoryDelta = false
        builderResult.inventoryDelta = nil
        return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        builderResult = Pogoprotos.Networking.Responses.GetInventoryResponse()
        return self
      }
      override public func clone() throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        return try Pogoprotos.Networking.Responses.GetInventoryResponse.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Networking.Responses.GetInventoryResponse {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Networking.Responses.GetInventoryResponse {
        let returnMe:Pogoprotos.Networking.Responses.GetInventoryResponse = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Networking.Responses.GetInventoryResponse) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        if other == Pogoprotos.Networking.Responses.GetInventoryResponse() {
         return self
        }
        if other.hasSuccess {
             success = other.success
        }
        if (other.hasInventoryDelta) {
            try mergeInventoryDelta(other.inventoryDelta)
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            success = try input.readBool()

          case 18:
            let subBuilder:Pogoprotos.Inventory.InventoryDelta.Builder = Pogoprotos.Inventory.InventoryDelta.Builder()
            if hasInventoryDelta {
              try subBuilder.mergeFrom(inventoryDelta)
            }
            try input.readMessage(subBuilder, extensionRegistry:extensionRegistry)
            inventoryDelta = subBuilder.buildPartial()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        let resultDecodedBuilder = Pogoprotos.Networking.Responses.GetInventoryResponse.Builder()
        if let jsonValueSuccess = jsonMap["success"] as? Bool {
          resultDecodedBuilder.success = jsonValueSuccess
        }
        if let jsonValueInventoryDelta = jsonMap["inventoryDelta"] as? Dictionary<String,AnyObject> {
          resultDecodedBuilder.inventoryDelta = try Pogoprotos.Inventory.InventoryDelta.Builder.decodeToBuilder(jsonValueInventoryDelta).build()

        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Networking.Responses.GetInventoryResponse.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Networking.Responses.GetInventoryResponse.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
