// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "PlayerCamera.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Data { public struct Player { }}}

public func == (lhs: Pogoprotos.Data.Player.PlayerCamera, rhs: Pogoprotos.Data.Player.PlayerCamera) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasIsDefaultCamera == rhs.hasIsDefaultCamera) && (!lhs.hasIsDefaultCamera || lhs.isDefaultCamera == rhs.isDefaultCamera)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Pogoprotos.Data.Player {
  public struct PlayerCameraRoot {
    public static var sharedInstance : PlayerCameraRoot {
     struct Static {
         static let instance : PlayerCameraRoot = PlayerCameraRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class PlayerCamera : GeneratedMessage, GeneratedMessageProtocol {
    public private(set) var hasIsDefaultCamera:Bool = false
    public private(set) var isDefaultCamera:Bool = false

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasIsDefaultCamera {
        try output.writeBool(1, value:isDefaultCamera)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasIsDefaultCamera {
        serialize_size += isDefaultCamera.computeBoolSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Data.Player.PlayerCamera> {
      var mergedArray = Array<Pogoprotos.Data.Player.PlayerCamera>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Player.PlayerCamera? {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Data.Player.PlayerCameraRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Data.Player.PlayerCamera.Builder {
      return Pogoprotos.Data.Player.PlayerCamera.classBuilder() as! Pogoprotos.Data.Player.PlayerCamera.Builder
    }
    public func getBuilder() -> Pogoprotos.Data.Player.PlayerCamera.Builder {
      return classBuilder() as! Pogoprotos.Data.Player.PlayerCamera.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Player.PlayerCamera.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Player.PlayerCamera.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
      return try Pogoprotos.Data.Player.PlayerCamera.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Data.Player.PlayerCamera) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasIsDefaultCamera {
        jsonMap["isDefaultCamera"] = isDefaultCamera
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Data.Player.PlayerCamera {
      return try Pogoprotos.Data.Player.PlayerCamera.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasIsDefaultCamera {
        output += "\(indent) isDefaultCamera: \(isDefaultCamera) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIsDefaultCamera {
               hashCode = (hashCode &* 31) &+ isDefaultCamera.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Data.Player.PlayerCamera"
    }
    override public func className() -> String {
        return "Pogoprotos.Data.Player.PlayerCamera"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Data.Player.PlayerCamera.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Data.Player.PlayerCamera = Pogoprotos.Data.Player.PlayerCamera()
      public func getMessage() -> Pogoprotos.Data.Player.PlayerCamera {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasIsDefaultCamera:Bool {
           get {
                return builderResult.hasIsDefaultCamera
           }
      }
      public var isDefaultCamera:Bool {
           get {
                return builderResult.isDefaultCamera
           }
           set (value) {
               builderResult.hasIsDefaultCamera = true
               builderResult.isDefaultCamera = value
           }
      }
      public func setIsDefaultCamera(value:Bool) -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        self.isDefaultCamera = value
        return self
      }
      public func clearIsDefaultCamera() -> Pogoprotos.Data.Player.PlayerCamera.Builder{
           builderResult.hasIsDefaultCamera = false
           builderResult.isDefaultCamera = false
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        builderResult = Pogoprotos.Data.Player.PlayerCamera()
        return self
      }
      override public func clone() throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        return try Pogoprotos.Data.Player.PlayerCamera.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Data.Player.PlayerCamera {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Data.Player.PlayerCamera {
        let returnMe:Pogoprotos.Data.Player.PlayerCamera = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Data.Player.PlayerCamera) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        if other == Pogoprotos.Data.Player.PlayerCamera() {
         return self
        }
        if other.hasIsDefaultCamera {
             isDefaultCamera = other.isDefaultCamera
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            isDefaultCamera = try input.readBool()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        let resultDecodedBuilder = Pogoprotos.Data.Player.PlayerCamera.Builder()
        if let jsonValueIsDefaultCamera = jsonMap["isDefaultCamera"] as? Bool {
          resultDecodedBuilder.isDefaultCamera = jsonValueIsDefaultCamera
        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Data.Player.PlayerCamera.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Data.Player.PlayerCamera.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
