// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "BattleType.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Data { public struct Battle { }}}

public extension Pogoprotos.Data.Battle {
  public struct BattleTypeRoot {
    public static var sharedInstance : BattleTypeRoot {
     struct Static {
         static let instance : BattleTypeRoot = BattleTypeRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }



  //Enum type declaration start 

  public enum BattleType:Int32, CustomDebugStringConvertible, CustomStringConvertible {
    case BattleTypeUnset = 0
    case Normal = 1
    case Training = 2
    public func toString() -> String {
      switch self {
      case .BattleTypeUnset: return "BATTLE_TYPE_UNSET"
      case .Normal: return "NORMAL"
      case .Training: return "TRAINING"
      }
    }
    public static func fromString(str:String) throws -> Pogoprotos.Data.Battle.BattleType {
      switch str {
      case "BATTLE_TYPE_UNSET":  return .BattleTypeUnset
      case "NORMAL":  return .Normal
      case "TRAINING":  return .Training
      default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
      }
    }
    public var debugDescription:String { return getDescription() }
    public var description:String { return getDescription() }
    private func getDescription() -> String { 
        switch self {
            case .BattleTypeUnset: return ".BattleTypeUnset"
            case .Normal: return ".Normal"
            case .Training: return ".Training"
        }
    }
  }

  //Enum type declaration end 

}

// @@protoc_insertion_point(global_scope)
