// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "ReleasePokemonResponse.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Pogoprotos { public struct Networking { public struct Responses { }}}

public func == (lhs: Pogoprotos.Networking.Responses.ReleasePokemonResponse, rhs: Pogoprotos.Networking.Responses.ReleasePokemonResponse) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasResult == rhs.hasResult) && (!lhs.hasResult || lhs.result == rhs.result)
  fieldCheck = fieldCheck && (lhs.hasCandyAwarded == rhs.hasCandyAwarded) && (!lhs.hasCandyAwarded || lhs.candyAwarded == rhs.candyAwarded)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Pogoprotos.Networking.Responses {
  public struct ReleasePokemonResponseRoot {
    public static var sharedInstance : ReleasePokemonResponseRoot {
     struct Static {
         static let instance : ReleasePokemonResponseRoot = ReleasePokemonResponseRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class ReleasePokemonResponse : GeneratedMessage, GeneratedMessageProtocol {


      //Enum type declaration start 

      public enum Result:Int32, CustomDebugStringConvertible, CustomStringConvertible {
        case Unset = 0
        case Success = 1
        case PokemonDeployed = 2
        case Failed = 3
        case ErrorPokemonIsEgg = 4
        public func toString() -> String {
          switch self {
          case .Unset: return "UNSET"
          case .Success: return "SUCCESS"
          case .PokemonDeployed: return "POKEMON_DEPLOYED"
          case .Failed: return "FAILED"
          case .ErrorPokemonIsEgg: return "ERROR_POKEMON_IS_EGG"
          }
        }
        public static func fromString(str:String) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result {
          switch str {
          case "UNSET":  return .Unset
          case "SUCCESS":  return .Success
          case "POKEMON_DEPLOYED":  return .PokemonDeployed
          case "FAILED":  return .Failed
          case "ERROR_POKEMON_IS_EGG":  return .ErrorPokemonIsEgg
          default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
          }
        }
        public var debugDescription:String { return getDescription() }
        public var description:String { return getDescription() }
        private func getDescription() -> String { 
            switch self {
                case .Unset: return ".Unset"
                case .Success: return ".Success"
                case .PokemonDeployed: return ".PokemonDeployed"
                case .Failed: return ".Failed"
                case .ErrorPokemonIsEgg: return ".ErrorPokemonIsEgg"
            }
        }
      }

      //Enum type declaration end 

    public private(set) var result:Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result = Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result.Unset
    public private(set) var hasResult:Bool = false
    public private(set) var hasCandyAwarded:Bool = false
    public private(set) var candyAwarded:Int32 = Int32(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasResult {
        try output.writeEnum(1, value:result.rawValue)
      }
      if hasCandyAwarded {
        try output.writeInt32(2, value:candyAwarded)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if (hasResult) {
        serialize_size += result.rawValue.computeEnumSize(1)
      }
      if hasCandyAwarded {
        serialize_size += candyAwarded.computeInt32Size(2)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Networking.Responses.ReleasePokemonResponse> {
      var mergedArray = Array<Pogoprotos.Networking.Responses.ReleasePokemonResponse>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse? {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Networking.Responses.ReleasePokemonResponseRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
      return Pogoprotos.Networking.Responses.ReleasePokemonResponse.classBuilder() as! Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder
    }
    public func getBuilder() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
      return classBuilder() as! Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Networking.Responses.ReleasePokemonResponse) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasResult {
        jsonMap["result"] = result.toString()
      }
      if hasCandyAwarded {
        jsonMap["candyAwarded"] = NSNumber(int:candyAwarded)
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
      return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if (hasResult) {
        output += "\(indent) result: \(result.description)\n"
      }
      if hasCandyAwarded {
        output += "\(indent) candyAwarded: \(candyAwarded) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasResult {
               hashCode = (hashCode &* 31) &+ Int(result.rawValue)
            }
            if hasCandyAwarded {
               hashCode = (hashCode &* 31) &+ candyAwarded.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Networking.Responses.ReleasePokemonResponse"
    }
    override public func className() -> String {
        return "Pogoprotos.Networking.Responses.ReleasePokemonResponse"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Networking.Responses.ReleasePokemonResponse.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Networking.Responses.ReleasePokemonResponse = Pogoprotos.Networking.Responses.ReleasePokemonResponse()
      public func getMessage() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
          return builderResult
      }

      required override public init () {
         super.init()
      }
        public var hasResult:Bool{
            get {
                return builderResult.hasResult
            }
        }
        public var result:Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result {
            get {
                return builderResult.result
            }
            set (value) {
                builderResult.hasResult = true
                builderResult.result = value
            }
        }
        public func setResult(value:Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result) -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
          self.result = value
          return self
        }
        public func clearResult() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
           builderResult.hasResult = false
           builderResult.result = .Unset
           return self
        }
      public var hasCandyAwarded:Bool {
           get {
                return builderResult.hasCandyAwarded
           }
      }
      public var candyAwarded:Int32 {
           get {
                return builderResult.candyAwarded
           }
           set (value) {
               builderResult.hasCandyAwarded = true
               builderResult.candyAwarded = value
           }
      }
      public func setCandyAwarded(value:Int32) -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        self.candyAwarded = value
        return self
      }
      public func clearCandyAwarded() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder{
           builderResult.hasCandyAwarded = false
           builderResult.candyAwarded = Int32(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        builderResult = Pogoprotos.Networking.Responses.ReleasePokemonResponse()
        return self
      }
      override public func clone() throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Networking.Responses.ReleasePokemonResponse {
        let returnMe:Pogoprotos.Networking.Responses.ReleasePokemonResponse = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Networking.Responses.ReleasePokemonResponse) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        if other == Pogoprotos.Networking.Responses.ReleasePokemonResponse() {
         return self
        }
        if other.hasResult {
             result = other.result
        }
        if other.hasCandyAwarded {
             candyAwarded = other.candyAwarded
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            let valueIntresult = try input.readEnum()
            if let enumsresult = Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result(rawValue:valueIntresult){
                 result = enumsresult
            } else {
                 try unknownFieldsBuilder.mergeVarintField(1, value:Int64(valueIntresult))
            }

          case 16:
            candyAwarded = try input.readInt32()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        let resultDecodedBuilder = Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder()
        if let jsonValueResult = jsonMap["result"] as? String {
          resultDecodedBuilder.result = try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Result.fromString(jsonValueResult)
        }
        if let jsonValueCandyAwarded = jsonMap["candyAwarded"] as? NSNumber {
          resultDecodedBuilder.candyAwarded = jsonValueCandyAwarded.intValue
        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Networking.Responses.ReleasePokemonResponse.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
